import Head from 'next/head';
import { sanityClient, urlFor } from '../lib/sanity';
import Link from 'next/dist/client/link';
import Image from 'next/image';
const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {
  return (
    <>
      <div>
        <Head>
          <title>Delicious Food</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
      </div>
      <h1>Welcome to Delicious Food</h1>
      <ul className='recipes-list'>
        {recipes?.length &&
          recipes.map((recipe) => (
            <li key={recipe._id} className='recipes-card'>
              <Link href={`recipes/${recipe.slug.current}`}>
                <a>
                  <div className='image-wrapper'>
                    <Image
                      alt={recipe.name}
                      width='100%'
                      height='100%'
                      layout='fill'
                      objectFit='cover'
                      src={urlFor(recipe.mainImage).width(800).url()}
                    />
                  </div>
                </a>
              </Link>
              <span>{recipe.name}</span>
            </li>
          ))}
      </ul>
    </>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return {
    props: { recipes },
  };
}
